{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Ride Share API",
    "description" : "`API` for **COS 243** Semester Project",
    "version" : "0.1.0"
  },
  "tags" : [ {
    "name" : "user",
    "description" : "Ride Share users"
  }, {
    "name" : "vehicle-type",
    "description" : "Vehicle types"
  }, {
    "name" : "vehicle",
    "description" : "Ride Share vehicles"
  }, {
    "name" : "driver",
    "description" : "Ride Share drivers"
  }, {
    "name" : "ride",
    "description" : "Ride Share rides"
  }, {
    "name" : "location",
    "description" : "Ride Share locations"
  }, {
    "name" : "driver-ride",
    "description" : "Relationship between driver and ride"
  }, {
    "name" : "driver-vehicle",
    "description" : "Relationship between driver and vehicle"
  }, {
    "name" : "user-ride",
    "description" : "Relationship between user and ride"
  } ],
  "components" : {
    "schemas" : {
      "Error" : {
        "description" : "Generic error message",
        "type" : "object",
        "properties" : {
          "message" : {
            "type" : "string"
          }
        },
        "example" : {
          "message" : "Something strange happened."
        }
      },
      "User" : {
        "description" : "Each user of **Ride Share**",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "firstName" : {
            "type" : "string"
          },
          "lastName" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          },
          "phone" : {
            "type" : "string"
          },
          "isAdmin" : {
            "type" : "boolean"
          }
        },
        "example" : {
          "id" : 42,
          "firstName" : "Fred",
          "lastName" : "Ziffle",
          "email" : "fred@example.com",
          "password" : "super-secret-thing",
          "phone" : "765-555-1212",
          "isAdmin" : false
        }
      },
      "VehicleType" : {
        "description" : "Type of a vehicle",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "vehicleType" : {
            "type" : "string"
          }
        },
        "example" : {
          "id" : 42,
          "type" : "Pickup Truck"
        }
      },
      "Driver" : {
        "description" : "Each driver of **Ride Share**",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "userId" : {
            "type" : "integer"
          },
          "licenseNumber" : {
            "type" : "integer"
          },
          "licenseState" : {
            "type" : "string"
          }
        },
        "example" : {
          "id" : 42,
          "userId" : 42,
          "licenseNumber" : 1245665313,
          "licenseState" : "IN"
        }
      },
      "Ride" : {
        "description" : "Each ride of **Ride Share**",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "date" : {
            "type" : "string"
          },
          "time" : {
            "type" : "string"
          },
          "distance" : {
            "type" : "number"
          },
          "fuelPrice" : {
            "type" : "number"
          },
          "fee" : {
            "type" : "number"
          },
          "vehicleId" : {
            "type" : "integer"
          },
          "fromLocationId" : {
            "type" : "integer"
          },
          "toLocationId" : {
            "type" : "integer"
          }
        },
        "example" : {
          "id" : 42,
          "date" : "10/20/2020",
          "time" : "11:40am",
          "distance" : 100.3,
          "fuelPrice" : 5.0,
          "fee" : 11.99,
          "vehicleId" : 42,
          "fromLocationId" : 42,
          "toLocationId" : 43
        }
      },
      "Location" : {
        "description" : "Each location of **Ride Share**",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "name" : {
            "type" : "string"
          },
          "address" : {
            "type" : "string"
          },
          "city" : {
            "type" : "string"
          },
          "state" : {
            "type" : "string"
          },
          "zipCode" : {
            "type" : "string"
          }
        },
        "example" : {
          "id" : 42,
          "name" : "City Hall",
          "address" : "412 New City st.",
          "city" : "New City",
          "state" : "IN",
          "zipCode" : 47602
        }
      },
      "Vehicle" : {
        "description" : "Each vehicles of **Ride Share**",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "make" : {
            "type" : "string"
          },
          "model" : {
            "type" : "string"
          },
          "color" : {
            "type" : "string"
          },
          "vehicleTypeId" : {
            "type" : "integer"
          },
          "capacity" : {
            "type" : "integer"
          },
          "mpg" : {
            "type" : "number"
          },
          "licenseState" : {
            "type" : "string"
          },
          "licensePlate" : {
            "type" : "string"
          }
        },
        "example" : {
          "id" : 42,
          "make" : "Honda",
          "model" : "Accord",
          "color" : "blue",
          "vehicleTypeId" : 41,
          "capacity" : 5,
          "mpg" : 50.5,
          "licenseSate" : "IN",
          "licensePlate" : "483fg7"
        }
      },
      "Driver-Ride" : {
        "description" : "Relationship between driver and ride",
        "type" : "object",
        "properties" : {
          "driverId" : {
            "type" : "integer"
          },
          "rideId" : {
            "type" : "integer"
          }
        },
        "example" : {
          "driverId" : 42,
          "rideId" : 42
        }
      },
      "Driver-Vehicle" : {
        "description" : "Relationship between driver and vehicle",
        "type" : "object",
        "properties" : {
          "driverId" : {
            "type" : "integer"
          },
          "vehicleId" : {
            "type" : "integer"
          }
        },
        "example" : {
          "driverId" : 42,
          "vehicleId" : 42
        }
      },
      "User-Ride" : {
        "description" : "Relationship between user and ride",
        "type" : "object",
        "properties" : {
          "userId" : {
            "type" : "integer"
          },
          "rideId" : {
            "type" : "integer"
          }
        },
        "example" : {
          "userId" : 42,
          "rideId" : 42
        }
      }
    }
  },
  "paths" : {
    "/users" : {
      "summary" : "Operations on users",
      "get" : {
        "summary" : "Get all users",
        "tags" : [ "user" ],
        "responses" : {
          "200" : {
            "description" : "All users fetched successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/User"
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "summary" : "Create a new user",
        "tags" : [ "user" ],
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/User"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "Created sucessfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "userId" : {
                      "type" : "integer"
                    }
                  },
                  "example" : {
                    "userId" : 42
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "Not created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error"
                },
                "example" : {
                  "message" : "Duplicate email address"
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}" : {
      "summary" : "Operations on a single user",
      "get" : {
        "summary" : "Get user by ID",
        "tags" : [ "user" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "description" : "ID of user to fetch",
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successfully retrieved",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/User"
                }
              }
            }
          },
          "400" : {
            "description" : "User not found"
          }
        }
      }
    },
    "/vehicles" : {
      "summary" : "Operations on vehicles",
      "get" : {
        "summary" : "Get all vehicles",
        "tags" : [ "vehicle" ],
        "responses" : {
          "200" : {
            "description" : "All vehicles fetched successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Vehicle"
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "summary" : "Create a new vehicle",
        "tags" : [ "vehicle" ],
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Vehicle"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "Created sucessfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Vehicle"
                }
              }
            }
          },
          "400" : {
            "description" : "Not created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error"
                },
                "example" : {
                  "message" : "Duplicate license plate"
                }
              }
            }
          }
        }
      }
    },
    "/vehicles{id}" : {
      "get" : {
        "summary" : "Get vehicle by ID",
        "tags" : [ "vehicle" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "description" : "ID of vehicle to fetch",
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successfully retrieved",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Vehicle"
                }
              }
            }
          },
          "400" : {
            "description" : "Vehicle not found"
          }
        }
      },
      "patch" : {
        "summary" : "Update an existing vehicle",
        "tags" : [ "vehicle" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "requestBody" : {
          "description" : "Updated vehicle",
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Vehicle"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/VehicleType"
                }
              }
            }
          },
          "400" : {
            "description" : "No such vehicle ID"
          }
        }
      }
    },
    "/vehicle-types" : {
      "post" : {
        "summary" : "Create a new vehicle type.",
        "description" : "_Each_ vehicle in **Ride Share** has a `type`, making it easier for riders to identify the vehicle.",
        "tags" : [ "vehicle-type" ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "object",
                "properties" : {
                  "vehicleType" : {
                    "type" : "string"
                  }
                },
                "example" : {
                  "vehicleType" : "Pickup Truck"
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "New vehicle type created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/VehicleType"
                }
              }
            }
          }
        }
      },
      "get" : {
        "summary" : "Retrieve all vehicle types",
        "tags" : [ "vehicle-type" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/VehicleType"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/vehicle-types/{id}" : {
      "patch" : {
        "summary" : "Update an existing vehicle type",
        "tags" : [ "vehicle-type" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "requestBody" : {
          "description" : "Updated vehicle type",
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "object",
                "properties" : {
                  "vehicleType" : {
                    "type" : "string"
                  }
                },
                "example" : {
                  "vehicleType" : "SUV"
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/VehicleType"
                }
              }
            }
          },
          "400" : {
            "description" : "No such vehicle ID"
          }
        }
      },
      "delete" : {
        "summary" : "Delete an existing vehicle type",
        "tags" : [ "vehicle-type" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "Vehicle deleted"
          },
          "400" : {
            "description" : "Can't delete vehicle"
          }
        }
      }
    },
    "/drivers" : {
      "summary" : "Operations related to all drivers",
      "post" : {
        "summary" : "Create a new driver",
        "tags" : [ "driver" ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Driver"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "New vehicle type created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Driver"
                }
              }
            }
          }
        }
      },
      "get" : {
        "summary" : "Retrieve all drivers",
        "tags" : [ "driver" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Driver"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/drivers/{id}" : {
      "summary" : "Operations on a single driver",
      "delete" : {
        "summary" : "Delete an existing driver",
        "tags" : [ "driver" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "Driver deleted"
          },
          "400" : {
            "description" : "Can't delete driver"
          }
        }
      }
    },
    "/drivers{driverId}/vehicles{vehicleId}" : {
      "summary" : "Operations relating to authorizations",
      "post" : {
        "summary" : "Add authorization to driver",
        "tags" : [ "driver-vehicle" ],
        "parameters" : [ {
          "name" : "driverId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        }, {
          "name" : "vehicleId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "New authorization added",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Driver-Vehicle"
                }
              }
            }
          }
        }
      },
      "delete" : {
        "summary" : "Delete an existing authorization",
        "tags" : [ "driver-vehicle" ],
        "parameters" : [ {
          "name" : "driverId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        }, {
          "name" : "vehicleId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "Authorization deleted"
          },
          "400" : {
            "description" : "Can't delete authorization"
          }
        }
      }
    },
    "/drivers{driverId}/rides{rideId}" : {
      "summary" : "Operations relating to relations between drivers and rides",
      "post" : {
        "summary" : "Add driver to ride",
        "tags" : [ "driver-ride" ],
        "parameters" : [ {
          "name" : "driverId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        }, {
          "name" : "rideId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "New authorization added",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Driver-Ride"
                }
              }
            }
          }
        }
      },
      "delete" : {
        "summary" : "Remove driver from ride",
        "tags" : [ "driver-ride" ],
        "parameters" : [ {
          "name" : "driverId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        }, {
          "name" : "rideId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "Driver removed from ride"
          },
          "400" : {
            "description" : "Can't remove driver from ride"
          }
        }
      }
    },
    "/users{userId}/rides{rideId}" : {
      "summary" : "Operations relating to user-ride relationships",
      "post" : {
        "summary" : "Add user to ride",
        "tags" : [ "user-ride" ],
        "parameters" : [ {
          "name" : "userId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        }, {
          "name" : "rideId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "New authorization added",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/User-Ride"
                }
              }
            }
          }
        }
      },
      "delete" : {
        "summary" : "Remove user from ride",
        "tags" : [ "user-ride" ],
        "parameters" : [ {
          "name" : "userId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        }, {
          "name" : "rideId",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "Authorization deleted"
          },
          "400" : {
            "description" : "Can't delete authorization"
          }
        }
      }
    },
    "/rides" : {
      "summary" : "Operations on rides",
      "get" : {
        "summary" : "Get all rides",
        "tags" : [ "ride" ],
        "responses" : {
          "200" : {
            "description" : "All rides fetched successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Ride"
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "summary" : "Create a new ride",
        "tags" : [ "ride" ],
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Ride"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "Created sucessfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Ride"
                }
              }
            }
          },
          "400" : {
            "description" : "Not created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error"
                },
                "example" : {
                  "message" : "Duplicate ride"
                }
              }
            }
          }
        }
      }
    },
    "/rides{id}" : {
      "summary" : "Operations on a single ride",
      "get" : {
        "summary" : "Get ride by ID",
        "tags" : [ "ride" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "description" : "ID of ride to fetch",
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successfully retrieved",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Ride"
                }
              }
            }
          },
          "400" : {
            "description" : "Ride not found"
          }
        }
      },
      "patch" : {
        "summary" : "Update an existing ride",
        "tags" : [ "ride" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "requestBody" : {
          "description" : "Updated ride",
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Ride"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Ride"
                }
              }
            }
          },
          "400" : {
            "description" : "No such ride ID"
          }
        }
      }
    },
    "/locations" : {
      "summary" : "Operations on locations",
      "get" : {
        "summary" : "Get all locations",
        "tags" : [ "location" ],
        "responses" : {
          "200" : {
            "description" : "All locations fetched successfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/Location"
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "summary" : "Create a new location",
        "tags" : [ "location" ],
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Location"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "Created sucessfully",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Location"
                }
              }
            }
          },
          "400" : {
            "description" : "Not created",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Error"
                },
                "example" : {
                  "message" : "Duplicate location"
                }
              }
            }
          }
        }
      }
    },
    "/locations{id}" : {
      "summary" : "Operations on a single location",
      "get" : {
        "summary" : "Get location by ID",
        "tags" : [ "location" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "description" : "ID of location to fetch",
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successfully retrieved",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Location"
                }
              }
            }
          },
          "400" : {
            "description" : "Location not found"
          }
        }
      },
      "patch" : {
        "summary" : "Update an existing location",
        "tags" : [ "location" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "schema" : {
            "type" : "integer"
          },
          "required" : true
        } ],
        "requestBody" : {
          "description" : "Updated location",
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Location"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Location"
                }
              }
            }
          },
          "400" : {
            "description" : "No such location ID"
          }
        }
      }
    }
  }
}